### ISSUE TITLE
Serious question about silliness

### ISSUE THREAD

**Issue by anthonygarvan** [18F/core-values#8]
A big part of the standard startup package in the private sector is a culture of playfulness. This not only helps attract and retain talent, it is also and important part of bonding and keeping people in a creative mindset. This could mean ping pong tables in the break room, video games at at lunch, or outings to trampoline dodge ball, for example. 

That sort of thing might not fly for civil servants (headline of Washington Post: "Federal Employees Playing Smash Brothers on Your Dime!"). How does 18F keep things light and fun without coming off as wasteful or disrespectful? Or do you instead take the stance that everything you do is Serious Work and the real fun of 18F is more about having a big impact?

Very interested how you are porting that aspect of startup culture, seems like a tricky issue to me.

**Comment by mbland** [comment]
There are no ping-pong tables, or foosball tables, or beach volleyball courts, or multiple on-site cafes serving three square meals a day, or video games at lunch. There isn't so much of the brazen goofing-around you'd see in a typical developers' den. No ski trips, or themed holiday parties with hired actors, or company-branded bike helmets stuffed with $1K bonus cash handed out at year's end. (Or microkitchens; I _do_ miss making my own lattes.)

That said, we have our fun. We're a real cast of characters, and we crack each other up quite often with our sparkling wit. Our work environment is very encouraging of creativity and collaboration, which makes it all the more gratifying when we exceed our clients' expectations, or see our influence manifest across government (and even bits of the broader tech industry) in other ways. Plus, there are rather frequent after-hours outings, a significant number of which involve [a particular video game](http://killerqueenarcade.com) (we are all intimately familiar with the Three Paths to Victory).

That said, I think the lot of us were drawn to 18F by the prospect of making a meaningful difference in people's lives through service to our country, and that gives our culture a spark you don't find in other tech teams. (I'll spare you my contrasting, unfiltered, not-necessarily-representing-18F-or-the-federal-government, far less flattering interpretation of typical tech company perks.) After all, bringing the federal government up-to-speed with modern industry practices isn't just a technical challenge, it's the ultimate cultural/organizational hack, and the prospect of helping generate massive, meaningful real-world impact as part of a high functioning team (and, speaking of the [US Digital Service](https://wh.gov/usds/) more broadly, as part of a family of high functioning teams) is a big part of the fun. That brand of shared motivation attracts some very interesting and talented people; so interesting and talented that I, at least, often don't notice the lack of games, cafes, parties, or microkitchens.

**Comment by anthonygarvan** [comment]
Great vision, thanks for laying it out. Agreed - a good latte is not a substitute for meaningful work that makes has a big positive impact.

**Comment by gboone** [comment]
+1 to everything @mbland said. I'll also add, we might not have the kitchens, or in-house dry cleaning, or nap pods, or 18F buses with WiFi and while we still manage to have fun in all the ways listed above, you can also go home at the end of the day, hang out with your dog, your kids, or your friends, and not think about work until you come back at 9am, and that is totally OK.

**Comment by leahbannon** [comment]
Aw @mbland, that's so well put. + :100:

**Comment by meiqimichelle** [comment]
+1 @mbland ! That was beautiful.

**Comment by harrisj** [comment]
Gender is another field we should probably have a discussion about. I guess the question I am wondering with some of these additional fields is should we consider the difference between _I am_ vs. _I am applying in programs for_...

**Comment by catherinedevlin** [comment]
Incidentally, we remote 18Fers get to enjoy everybody's razor wit and awesome jokes via online chat, whereas ping-pong, catered parties, etc. would only be available in-office; that could make remote folks feel cut off from the team.

I will thank DC and SF staff for refraining from saying funny things out loud in the office, however.  When you think of something funny, please type it into chat and silently gesture to your officemates to read it there so that remote workers can enjoy equitably.  :)

**Comment by anthonygarvan** [comment]
lol

**Comment by gbinal** [comment]
Personally, I just watch a lot of Community and let that inspire me.  


![Troy and Abed](https://33.media.tumblr.com/9718ab1960ca4242a144719721731e1c/tumblr_mh5ql5UiIJ1qivoo8o1_500.gif)

**Comment by NoahKunin** [comment]
Love the thread, closing just as part of normal repo O&M.
